package br.com.solicitacoes.solicitacoes.domain;

public enum HistoricoTipo {
	CLIENTE_NEW, SOLICITACAO_ABERTA, SOLICITACAO_ATRASADA, SOLICITACAO_EDIT, SOLICITACAO_PENDENTE, SOLUCAO_EDIT, CLIENTE_EDIT, SOLICITACAO_FINALIZADA;
}
